name: Pull Request validation

on: [pull_request]


jobs:
  project_4-contracts-ci:
    name: Run project_4-contracts validation
    uses: ./.github/workflows/project_4-contracts-ci.yaml

  project_4-frontend-ci:
    name: Run project_4-frontend validation
    uses: ./.github/workflows/project_4-frontend-ci.yaml

